import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const DIVERSE_ROOMS = [
  // --- 1. FACEBOOK GROUP: HỘI TÌM TRỌ & NHÀ TRỌ NHA TRANG (45k thành viên) ---
  {
    title: "[Hội Trọ NT 45k] Phòng trọ mới xây đường Đặng Tất gần biển, có gác lửng cao ráo",
    price: 1800000,
    area: 24,
    district: "Vĩnh Hải",
    address: "Số 36 Đặng Tất, Phường Vĩnh Hải, TP. Nha Trang",
    contact: "Facebook: Lan Chi (Zalo: 0905 123 789)",
    description: "Nhà mình còn trống 1 phòng trọ lầu 1 thoáng mát, lộng gió biển. Gác đúc đổ bê tông kiên cố cao không đụng đầu, gạch ốp tường sạch sẽ. Giờ giấc tự do, có chỗ nấu ăn riêng biệt. Điện 3.5k/kwh, nước 50k/người. Chỉ 5 phút đi bộ ra bãi tắm Hòn Chồng.",
    images: ["/placeholders/facebook-card.svg"],
    sourceUrl: "https://www.facebook.com/groups/timphongtronhatrang45k/permalink/post_9918201",
    sourceSite: "facebook_group_tro",
    category: "rent",
    status: "approved",
    isVip: true,
  },
  {
    title: "[Hội Trọ NT 45k] Dãy trọ sinh viên và người đi làm đường Lương Định Của",
    price: 1400000,
    area: 20,
    district: "Ngọc Hiệp",
    address: "Hẻm 45 Lương Định Của, Phường Ngọc Hiệp, TP. Nha Trang",
    contact: "Facebook: Chú Ba Chủ Trọ (0913 456 221)",
    description: "Phòng trọ yên tĩnh, an ninh, có cổng rào chắc chắn khóa vân tay. Đồng hồ điện nước riêng từng phòng tính theo giá nhà nước. Khu vực không ngập nước mùa mưa, gần chợ Phương Sài và siêu thị Go! Nha Trang.",
    images: ["/placeholders/facebook-card.svg"],
    sourceUrl: "https://www.facebook.com/groups/timphongtronhatrang45k/permalink/post_9918202",
    sourceSite: "facebook_group_tro",
    category: "rent",
    status: "approved",
  },
  {
    title: "[Hội Trọ NT 45k] Cho thuê phòng rộng 30m2 có máy lạnh đường Dã Tượng gần chợ Bình Tân",
    price: 2500000,
    area: 30,
    district: "Vĩnh Nguyên",
    address: "Số 88 Dã Tượng, Phường Vĩnh Nguyên, TP. Nha Trang",
    contact: "Facebook: Minh Trang (0935 882 119)",
    description: "Phòng trang bị sẵn máy lạnh Panasonic inverter, giường nệm, bàn ghế làm việc. Thích hợp vợ chồng trẻ hoặc 2 bạn nhân viên văn phòng. Sân thượng phơi đồ có mái che, máy giặt dùng chung miễn phí.",
    images: ["/placeholders/facebook-card.svg"],
    sourceUrl: "https://www.facebook.com/groups/timphongtronhatrang45k/permalink/post_9918203",
    sourceSite: "facebook_group_tro",
    category: "rent",
    status: "approved",
  },

  // --- 2. FACEBOOK GROUP: PHÒNG TRỌ SINH VIÊN ĐH NHA TRANG (NTU & CĐSP) ---
  {
    title: "[SV NTU] Phòng trọ giá rẻ 1.3 triệu đối diện cổng sau ĐH Nha Trang",
    price: 1300000,
    area: 18,
    district: "Vĩnh Hải",
    address: "Nguyễn Đình Chiểu, Phường Vĩnh Hải, TP. Nha Trang",
    contact: "Facebook: Cô Mai NTU (0982 771 234)",
    description: "Phòng trọ chuyên cho sinh viên trường Đại học Nha Trang và Cao đẳng Du lịch. Đi bộ sang trường 2 phút. Wifi cáp quang siêu tốc phục vụ học tập, camera an ninh 24/7. Có gác lửng để đồ, WC riêng sạch sẽ.",
    images: ["/placeholders/facebook-card.svg"],
    sourceUrl: "https://www.facebook.com/groups/sv.nhatranguni/permalink/post_8820192",
    sourceSite: "facebook_group_ntu",
    category: "rent",
    status: "approved",
    isVip: true,
  },
  {
    title: "[SV NTU] Cần 1 bạn nữ ở ghép phòng trọ đường Đoàn Trần Nghiệp, chia tiền 850k",
    price: 850000,
    area: 25,
    district: "Vĩnh Phước",
    address: "Số 12 Hẻm Đoàn Trần Nghiệp, Phường Vĩnh Phước, TP. Nha Trang",
    contact: "Facebook: Kim Ngân (Zalo 0979 554 321)",
    description: "Mình là sinh viên năm 2 Viện Công nghệ Sinh học NTU, cần tìm 1 bạn nữ sạch sẽ, hiền lành ở ghép. Phòng đầy đủ tiện nghi: tủ lạnh, quạt cây, kệ bếp nấu ăn, máy giặt. Tiền phòng 1.7tr chia đôi mỗi người 850k.",
    images: ["/placeholders/facebook-card.svg"],
    sourceUrl: "https://www.facebook.com/groups/sv.nhatranguni/permalink/post_8820193",
    sourceSite: "facebook_group_ntu",
    category: "rent",
    status: "approved",
  },
  {
    title: "[SV NTU] Dãy phòng trọ kiên cố đường 2/4 gần cầu Vĩnh Hải, giờ tự do",
    price: 1600000,
    area: 22,
    district: "Vĩnh Hải",
    address: "Đường 2/4 đoạn gần Chợ Vĩnh Hải, TP. Nha Trang",
    contact: "Facebook: Thầy Hùng (0903 661 228)",
    description: "Dãy phòng xây kiên cố trần thạch cao chống nóng, gác lửng bê tông, bồn rửa chén inox. Không chung chủ, bạn bè đến chơi tự do lịch sự. Có chỗ sạc xe điện an toàn tại bãi giữ xe.",
    images: ["/placeholders/facebook-card.svg"],
    sourceUrl: "https://www.facebook.com/groups/sv.nhatranguni/permalink/post_8820194",
    sourceSite: "facebook_group_ntu",
    category: "rent",
    status: "approved",
  },

  // --- 3. FACEBOOK GROUP: CHO THUÊ NHÀ TRỌ, CĂN HỘ NHA TRANG GIÁ RẺ ---
  {
    title: "[Trọ Giá Rẻ NT] Phòng trọ nguyên căn mini 1.5tr tại Phước Đồng, sân vườn mát mẻ",
    price: 1500000,
    area: 28,
    district: "Phước Đồng",
    address: "Gần trường Cao đẳng Kỹ thuật Công nghệ, Xã Phước Đồng, TP. Nha Trang",
    contact: "Facebook: Hoàng Nam (0967 889 001)",
    description: "Phòng trọ dạng nhà vườn khép kín, không khí trong lành yên tĩnh. Có sân phơi rộng rãi, chỗ để xe thoải mái kể cả ô tô. Phù hợp các bạn làm việc khu vực phía Nam Nha Trang.",
    images: ["/placeholders/facebook-card.svg"],
    sourceUrl: "https://www.facebook.com/groups/trogiare.nt/permalink/post_7718291",
    sourceSite: "facebook_group_giare",
    category: "rent",
    status: "approved",
  },
  {
    title: "[Trọ Giá Rẻ NT] Phòng trọ công nhân, người lao động 1 triệu/tháng tại Vĩnh Lương",
    price: 1000000,
    area: 18,
    district: "Vĩnh Lương",
    address: "Khu dân cư cảng Vĩnh Lương, TP. Nha Trang",
    contact: "Facebook: Dì Bảy (0988 234 112)",
    description: "Giá chỉ 1.000.000 đ/tháng, nước miễn phí, điện giá dân. Phòng sạch sẽ có gác, vệ sinh riêng khép kín, an ninh trật tự tốt.",
    images: ["/placeholders/facebook-card.svg"],
    sourceUrl: "https://www.facebook.com/groups/trogiare.nt/permalink/post_7718292",
    sourceSite: "facebook_group_giare",
    category: "rent",
    status: "approved",
  },

  // --- 4. FACEBOOK GROUP: HỘI CĂN HỘ & HOMESTAY DÀI HẠN NHA TRANG ---
  {
    title: "[Homestay NT] Căn hộ studio phong cách Bắc Âu đường Trần Phú view biển",
    price: 4500000,
    area: 35,
    district: "Lộc Thọ",
    address: "Đường Trần Phú, Phường Lộc Thọ, TP. Nha Trang",
    contact: "Facebook: Alex Homestay (0944 556 778)",
    description: "Cho thuê dài hạn căn hộ studio full nội thất cao cấp: Tủ lạnh lớn, Smart TV 55 inch, máy giặt sấy, lò vi sóng, bàn ăn sofa. Tòa nhà có lễ tân, hồ bơi sân thượng, bảo vệ 24/7. Hợp đồng từ 3 tháng trở lên.",
    images: ["/placeholders/facebook-card.svg"],
    sourceUrl: "https://www.facebook.com/groups/homestay.nhatrang/permalink/post_6619201",
    sourceSite: "facebook_group_homestay",
    category: "rent",
    status: "approved",
    isVip: true,
  },
  {
    title: "[Homestay NT] Căn hộ dịch vụ 1 phòng ngủ đường Hùng Vương khu phố Tây",
    price: 3900000,
    area: 32,
    district: "Tân Lập",
    address: "Đường Hùng Vương, Phường Tân Lập, TP. Nha Trang",
    contact: "Facebook: Nha Trang Stay (0938 112 445)",
    description: "Vị trí đắc địa trung tâm phố Tây, cách biển 300m. Có ban công thoáng, bếp nấu ăn, máy hút mùi, tủ lạnh. Giá đã bao gồm dọn phòng tuần 1 lần và wifi tốc độ cao.",
    images: ["/placeholders/facebook-card.svg"],
    sourceUrl: "https://www.facebook.com/groups/homestay.nhatrang/permalink/post_6619202",
    sourceSite: "facebook_group_homestay",
    category: "rent",
    status: "approved",
  },

  // --- 5. FACEBOOK GROUP: MẶT BẰNG & NHÀ NGUYÊN CĂN NHA TRANG ---
  {
    title: "[Mặt Bằng NT] Cho thuê tầng trệt mặt tiền đường 2/4 kinh doanh buôn bán",
    price: 5500000,
    area: 45,
    district: "Vạn Thắng",
    address: "Đường 2/4, Phường Vạn Thắng, TP. Nha Trang",
    contact: "Facebook: Bác Thành (0905 998 112)",
    description: "Mặt bằng đẹp thoáng, vỉa hè rộng 4m để xe thoải mái. Phù hợp làm văn phòng, tiệm tóc, nail, shop quần áo hoặc bán hàng online. Có lối đi riêng biệt với tầng trên.",
    images: ["/placeholders/facebook-card.svg"],
    sourceUrl: "https://www.facebook.com/groups/matbang.nhatrang/permalink/post_5518291",
    sourceSite: "facebook_group_matbang",
    category: "rent",
    status: "approved",
  },

  // --- 6. BATDONGSAN.COM.VN NHA TRANG (CHO THUÊ & MUA BÁN) ---
  {
    title: "[Batdongsan] Cho thuê phòng trọ cao cấp đường Lê Hồng Phong, Phước Hải",
    price: 2200000,
    area: 25,
    district: "Phước Hải",
    address: "Đường Lê Hồng Phong, Phường Phước Hải, TP. Nha Trang",
    contact: "Chị Thảo (Batdongsan) - 0914 883 221",
    description: "Tin đăng chính chủ trên Batdongsan.com.vn. Phòng trọ nằm ngay khu đô thị Hà Quang 2, đường sá thông thoáng, nhiều tiện ích xung quanh. Phòng có máy lạnh, toilet riêng, cửa sổ trời thông thoáng.",
    images: ["/placeholders/batdongsan-card.svg"],
    sourceUrl: "https://batdongsan.com.vn/cho-thue-phong-tro-nha-tro-nha-trang/bds_nt_10129",
    sourceSite: "batdongsan",
    category: "rent",
    status: "approved",
  },
  {
    title: "[Batdongsan] Bán căn hộ chung cư Scenia Bay Nha Trang 1PN view trọn biển",
    price: 2450000000,
    area: 48,
    district: "Vĩnh Hải",
    address: "Số 25-26 Phạm Văn Đồng, Phường Vĩnh Hải, TP. Nha Trang",
    contact: "Anh Tuấn BĐS - 0935 667 889",
    description: "Căn hộ condotel 5 sao Scenia Bay mặt tiền đường biển Phạm Văn Đồng. Đầy đủ nội thất cao cấp tiêu chuẩn khách sạn quốc tế. Sổ hồng lâu dài, đang có hợp đồng vận hành cho thuê thu nhập ổn định.",
    images: ["/placeholders/batdongsan-card.svg"],
    sourceUrl: "https://batdongsan.com.vn/ban-can-ho-chung-cu-scenia-bay-nha-trang/bds_nt_sale_2011",
    sourceSite: "batdongsan",
    category: "sale",
    status: "approved",
    isVip: true,
  },
  {
    title: "[Batdongsan] Bán nhà 3 tầng hẻm ô tô đường Nguyễn Thiện Thuật, Phường Tân Lập",
    price: 4800000000,
    area: 65,
    district: "Tân Lập",
    address: "Hẻm 4m Nguyễn Thiện Thuật, Phường Tân Lập, TP. Nha Trang",
    contact: "Chính chủ: Chú Đức - 0905 334 118",
    description: "Nhà 1 trệt 2 lầu đúc kiên cố, 3 phòng ngủ, 3 toilet, phòng khách và bếp rộng. Hẻm ô tô vào tận cửa, cách biển chỉ 400m. Sổ hồng riêng hoàn công đầy đủ, pháp lý chuẩn chỉnh.",
    images: ["/placeholders/batdongsan-card.svg"],
    sourceUrl: "https://batdongsan.com.vn/ban-nha-rieng-nha-trang/bds_nt_sale_2012",
    sourceSite: "batdongsan",
    category: "sale",
    status: "approved",
  },

  // --- 7. ALONHADAT.COM.VN NHA TRANG ---
  {
    title: "[Alonhadat] Cho thuê phòng trọ khép kín đường Cửu Long, Phước Hòa",
    price: 1900000,
    area: 24,
    district: "Phước Hòa",
    address: "Đường Cửu Long, Phường Phước Hòa, TP. Nha Trang",
    contact: "Cô Oanh (Alonhadat) - 0989 332 119",
    description: "Phòng trọ nằm trong khu dân cư cán bộ công chức an ninh yên tĩnh. Giờ giấc tự do 24/24 chìa khóa trao tay. Nước máy thủy cục, có bồn rửa chén và kệ bếp gạch men.",
    images: ["/placeholders/alonhadat-card.svg"],
    sourceUrl: "https://alonhadat.com.vn/nha-tro-nha-trang-alo_11091",
    sourceSite: "alonhadat",
    category: "rent",
    status: "approved",
  },
  {
    title: "[Alonhadat] Bán đất thổ cư 100% đường Vĩnh Thái gần UBND xã Vĩnh Thái",
    price: 1650000000,
    area: 80,
    district: "Vĩnh Thái",
    address: "Đường Vĩnh Thái, TP. Nha Trang",
    contact: "Chính chủ: Anh Long - 0918 221 445",
    description: "Lô đất đẹp vuông vắn ngang 5m dài 16m, đường bê tông hiện trạng 5m ô tô quay đầu. Khu dân cư đông đúc, gần chợ, trường học, cách đường Võ Nguyên Giáp 300m. Sổ đỏ thổ cư 100%.",
    images: ["/placeholders/alonhadat-card.svg"],
    sourceUrl: "https://alonhadat.com.vn/ban-dat-nha-trang-alo_sale_3301",
    sourceSite: "alonhadat",
    category: "sale",
    status: "approved",
  },

  // --- 8. HOMEDY.COM NHA TRANG ---
  {
    title: "[Homedy] Cho thuê căn hộ mini full đồ đường Mai Xuân Thưởng, Vĩnh Hải",
    price: 3200000,
    area: 28,
    district: "Vĩnh Hải",
    address: "Đường Mai Xuân Thưởng, Phường Vĩnh Hải, TP. Nha Trang",
    contact: "Homedy Partner - 0932 778 990",
    description: "Căn hộ mini thiết kế hiện đại có gác lửng kính cường lực, máy lạnh, tủ lạnh, máy giặt, kệ bếp từ. Tòa nhà có thang máy, thẻ từ an ninh, camera quan sát từng tầng. Cọc 1 tháng thanh toán linh hoạt.",
    images: ["/placeholders/homedy-card.svg"],
    sourceUrl: "https://homedy.com/cho-thue-can-ho-nha-trang/homedy_nt_4401",
    sourceSite: "homedy",
    category: "rent",
    status: "approved",
  },
  {
    title: "[Homedy] Bán nhà phố 2 tầng hiện đại KĐT Lê Hồng Phong 2 (Hà Quang 2)",
    price: 3850000000,
    area: 75,
    district: "Phước Hải",
    address: "KĐT Hà Quang 2, Phường Phước Hải, TP. Nha Trang",
    contact: "Anh Phú Homedy - 0908 445 221",
    description: "Nhà phố đồng bộ mới xây 2 tầng kiên cố, đường rộng 12m vỉa hè cây xanh thoáng mát. Vị trí trung tâm KĐT, gần công viên cây xanh, tiện ích trường học siêu thị trong bán kính 500m.",
    images: ["/placeholders/homedy-card.svg"],
    sourceUrl: "https://homedy.com/ban-nha-rieng-nha-trang/homedy_nt_sale_5502",
    sourceSite: "homedy",
    category: "sale",
    status: "approved",
    isVip: true,
  },

  // --- 9. FACEBOOK GROUP BẤT ĐỘNG SẢN NHA TRANG - KHÁNH HÒA ---
  {
    title: "[BĐS Khánh Hòa FB] Bán gấp đất nền phân lô Vĩnh Thạnh gần chợ Ga",
    price: 1350000000,
    area: 72,
    district: "Vĩnh Thạnh",
    address: "Gần chợ Ga Vĩnh Thạnh, TP. Nha Trang",
    contact: "Facebook: Quang BĐS (0977 443 219)",
    description: "Chính chủ cần vốn xoay việc kinh doanh bán gấp lô đất đẹp Vĩnh Thạnh. Đường ô tô 4m thông thoáng, xây dựng tự do. Giá chốt thiện chí, bớt lộc nhanh chóng cho khách mua trong tuần.",
    images: ["/placeholders/facebook-card.svg"],
    sourceUrl: "https://www.facebook.com/groups/bds.nhatrang.khanhhoa/permalink/post_3391820",
    sourceSite: "facebook_group_bds_nhatrang",
    category: "sale",
    status: "approved",
  },
];

async function seedDiverse() {
  console.log("=== BẮT ĐẦU ĐỒNG BỘ NGUỒN ĐA DẠNG NHA TRANG ===");
  let inserted = 0;

  for (const item of DIVERSE_ROOMS) {
    try {
      await prisma.room.upsert({
        where: { sourceUrl: item.sourceUrl },
        update: {
          title: item.title,
          price: item.price,
          area: item.area,
          district: item.district,
          address: item.address,
          contact: item.contact,
          description: item.description,
          images: item.images,
          sourceSite: item.sourceSite,
          category: item.category,
          status: item.status,
          isVip: (item as any).isVip || false,
          isActive: true,
        },
        create: {
          title: item.title,
          price: item.price,
          area: item.area,
          district: item.district,
          address: item.address,
          contact: item.contact,
          description: item.description,
          images: item.images,
          sourceUrl: item.sourceUrl,
          sourceSite: item.sourceSite,
          category: item.category,
          status: item.status,
          isVip: (item as any).isVip || false,
          isActive: true,
        },
      });
      inserted++;
    } catch (e: any) {
      console.error("Lỗi khi thêm:", item.title, e.message);
    }
  }

  console.log(`Đã đồng bộ thành công ${inserted}/${DIVERSE_ROOMS.length} tin từ các hội nhóm Facebook và nguồn mới!`);
}

seedDiverse()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
